from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://minesportal.rajasthan.gov.in/")

    def wait():
        page.wait_for_load_state("networkidle")

    wait()
    ok = page.get_by_role("button", name="OK")
    ok.click()
    username = page.get_by_placeholder("Username")
    password = page.get_by_placeholder("Password")
    username.fill("VENDOR00219")
    password.fill("Watsoo@0909")
    input("please Fill captcha and press enter")
    login = page.get_by_role("button", name="Login")
    login.click()
    # ok_button = page.get_by_role("button", name="OK")
    ok.click()
    gps_vendor = page.get_by_role("heading",name = "GPS Vendor")
    gps_vendor.click()
    wait()
    Device_tagging = page.get_by_text("Device Tagging")
    Device_tagging.click()
    Register_dvc = page.get_by_text("Register GPS Device")
    Register_dvc.click()
    wait()
    Add_dvc = page.get_by_role("button", name="Add Device")
    Add_dvc.click()
    # Vendor_name = page.locator('select[formcontrolname="vendorId"]')
    # Vendor_name.select_option(value="224")
    vendor = page.locator('select[formcontrolname="vendorId"]')
    vendor.select_option(label="WATSOO EXPRESS PRIVATE LIMITED")
    wait()

    test_req = page.locator('select[formcontrolname="requestNo"]')
    test_req.select_option(label="REQVEN-1-305")
    wait()

    Manuf_name = page.locator('select[formcontrolname="manufacturerName"]')
    Manuf_name.select_option(label="WATSOO EXPRESS PRIVATE LIMITED")
    wait()
    input("Press enter to close")
    browser.close()