from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    # page2 = browser.new_page()
    # page2.goto("https://www.youtube.com")
    page.goto("https://www.saucedemo.com/")
    Username = page.get_by_placeholder("Username")
    password = page.get_by_placeholder("password")
    login = page.get_by_role("button", name="login")
    Username.fill("standard_user")
    password.fill("secret_sauce")
    login.click()
    print("login clicked")
    page.get_by_text("Sauce Labs Backpack").click()
    print("text clicked")
    # page.get_by_role("button", name="Add to cart").click()
    add_to_cart = page.get_by_role("button", name="Add to cart").click()
    print("cart clicked")
    cart = page.get_by_test_id("shopping-cart-link")
    cart.click()
    print("cart link clicked")
    input("press enter to close")
    browser.close()